q_types_mapping = {
    'abnormality_color': 'color',
    'landmark_color': 'color',
    'abnormality_location': 'location',
    'instrument_location': 'location',
    'landmark_location': 'location',
    'finding_count': 'count',
    'instrument_count': 'count',
    'polyp_count': 'count',
    'abnormality_presence': 'yesno',
    'box_artifact_presence': 'yesno',
    'finding_presence': 'yesno',
    'instrument_presence': 'yesno',
    'landmark_presence': 'yesno',
    'text_presence': 'yesno',
    'polyp_removal_status': 'yesno',
    'polyp_type': 'single',
    'polyp_size': 'single',
    'procedure_type': 'single',
}
q_types = ["yesno", "single", "multi", "color", "location", "count"]